// ignore_for_file: public_member_api_docs, sort_constructors_first
// Copyright (C) 2023 Joan Schipper
//
// This file is part of animated_sliver_box.
//
// animated_sliver_box is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// animated_sliver_box is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with animated_sliver_box.  If not, see <http://www.gnu.org/licenses/>.

// Colors are from the site: https://www.colorhexa.com/color-names
//
//
//

import 'package:flutter/widgets.dart';

class ColorName {
  String name;
  Color color;

  ColorName({
    required this.name,
    required this.color,
  });
}

final someColors = [
  ColorName(name: 'Air Force blue', color: const Color(0XFF5d8aa8)),
  ColorName(name: 'Alice blue', color: const Color(0XFFf0f8ff)),
  ColorName(name: 'Alizarin crimson', color: const Color(0XFFe32636)),
  ColorName(name: 'Almond', color: const Color(0XFFefdecd)),
  ColorName(name: 'Amaranth', color: const Color(0XFFe52b50)),
  ColorName(name: 'Amber', color: const Color(0XFFffbf00)),
  ColorName(name: 'American rose', color: const Color(0XFFff033e)),
  ColorName(name: 'Amethyst', color: const Color(0XFF9966cc)),
  ColorName(name: 'Android Green', color: const Color(0XFFa4c639)),
  ColorName(name: 'Anti-flash white', color: const Color(0XFFf2f3f4)),
  ColorName(name: 'Antique brass', color: const Color(0XFFcd9575)),
  ColorName(name: 'Antique fuchsia', color: const Color(0XFF915c83)),
  ColorName(name: 'Antique white', color: const Color(0XFFfaebd7)),
  ColorName(name: 'Ao', color: const Color(0XFF008000)),
  ColorName(name: 'Apple green', color: const Color(0XFF8db600)),
  ColorName(name: 'Apricot', color: const Color(0XFFfbceb1)),
  ColorName(name: 'Aqua', color: const Color(0XFF00ffff)),
  ColorName(name: 'Aquamarine', color: const Color(0XFF7fffd4)),
  ColorName(name: 'Army green', color: const Color(0XFF4b5320)),
  ColorName(name: 'Arylide yellow', color: const Color(0XFFe9d66b)),
  ColorName(name: 'Ash grey', color: const Color(0XFFb2beb5)),
  ColorName(name: 'Asparagus', color: const Color(0XFF87a96b)),
  ColorName(name: 'Atomic tangerine', color: const Color(0XFFff9966)),
  ColorName(name: 'Auburn', color: const Color(0XFFa52a2a)),
  ColorName(name: 'Aureolin', color: const Color(0XFFfdee00)),
  ColorName(name: 'AuroMetalSaurus', color: const Color(0XFF6e7f80)),
  ColorName(name: 'Awesome', color: const Color(0XFFff2052)),
  ColorName(name: 'Azure', color: const Color(0XFF007fff)),
  ColorName(name: 'Azure mist/web', color: const Color(0XFFf0ffff)),
  ColorName(name: 'Baby blue', color: const Color(0XFF89cff0)),
  ColorName(name: 'Baby blue eyes', color: const Color(0XFFa1caf1)),
  ColorName(name: 'Baby pink', color: const Color(0XFFf4c2c2)),
  ColorName(name: 'Ball Blue', color: const Color(0XFF21abcd)),
  ColorName(name: 'Banana Mania', color: const Color(0XFFfae7b5)),
  ColorName(name: 'Banana yellow', color: const Color(0XFFffe135)),
  ColorName(name: 'Battleship grey', color: const Color(0XFF848482)),
  ColorName(name: 'Bazaar', color: const Color(0XFF98777b)),
  ColorName(name: 'Beau blue', color: const Color(0XFFbcd4e6)),
  ColorName(name: 'Beaver', color: const Color(0XFF9f8170)),
  ColorName(name: 'Beige', color: const Color(0XFFf5f5dc)),
  ColorName(name: 'Bisque', color: const Color(0XFFffe4c4)),
  ColorName(name: 'Bistre', color: const Color(0XFF3d2b1f)),
  ColorName(name: 'Bittersweet', color: const Color(0XFFfe6f5e)),
  ColorName(name: 'Black', color: const Color(0XFF000000)),
  ColorName(name: 'Blanched Almond', color: const Color(0XFFffebcd)),
  ColorName(name: 'Bleu de France', color: const Color(0XFF318ce7)),
  ColorName(name: 'Blizzard Blue', color: const Color(0XFFace5ee)),
  ColorName(name: 'Blond', color: const Color(0XFFfaf0be)),
  ColorName(name: 'Blue', color: const Color(0XFF0000ff)),
  ColorName(name: 'Blue Bell', color: const Color(0XFFa2a2d0)),
  ColorName(name: 'Blue Gray', color: const Color(0XFF6699cc)),
  ColorName(name: 'Blue green', color: const Color(0XFF0d98ba)),
  ColorName(name: 'Blue purple', color: const Color(0XFF8a2be2)),
  ColorName(name: 'Blue violet', color: const Color(0XFF8a2be2)),
  ColorName(name: 'Blush', color: const Color(0XFFde5d83)),
  ColorName(name: 'Bole', color: const Color(0XFF79443b)),
  ColorName(name: 'Bondi blue', color: const Color(0XFF0095b6)),
  ColorName(name: 'Bone', color: const Color(0XFFe3dac9)),
  ColorName(name: 'Boston University Red', color: const Color(0XFFcc0000)),
  ColorName(name: 'Bottle green', color: const Color(0XFF006a4e)),
  ColorName(name: 'Boysenberry', color: const Color(0XFF873260)),
  ColorName(name: 'Brandeis blue', color: const Color(0XFF0070ff)),
  ColorName(name: 'Brass', color: const Color(0XFFb5a642)),
  ColorName(name: 'Brick red', color: const Color(0XFFcb4154)),
  ColorName(name: 'Bright cerulean', color: const Color(0XFF1dacd6)),
  ColorName(name: 'Bright green', color: const Color(0XFF66ff00)),
  ColorName(name: 'Bright lavender', color: const Color(0XFFbf94e4)),
  ColorName(name: 'Bright maroon', color: const Color(0XFFc32148)),
  ColorName(name: 'Bright pink', color: const Color(0XFFff007f)),
  ColorName(name: 'Bright turquoise', color: const Color(0XFF08e8de)),
  ColorName(name: 'Bright ube', color: const Color(0XFFd19fe8)),
  ColorName(name: 'Brilliant lavender', color: const Color(0XFFf4bbff)),
  ColorName(name: 'Brilliant rose', color: const Color(0XFFff55a3)),
  ColorName(name: 'Brink pink', color: const Color(0XFFfb607f)),
  ColorName(name: 'British racing green', color: const Color(0XFF004225)),
  ColorName(name: 'Bronze', color: const Color(0XFFcd7f32)),
  ColorName(name: 'Brown', color: const Color(0XFFa52a2a)),
  ColorName(name: 'Bubble gum', color: const Color(0XFFffc1cc)),
  ColorName(name: 'Bubbles', color: const Color(0XFFe7feff)),
  ColorName(name: 'Buff', color: const Color(0XFFf0dc82)),
  ColorName(name: 'Bulgarian rose', color: const Color(0XFF480607)),
  ColorName(name: 'Burgundy', color: const Color(0XFF800020)),
  ColorName(name: 'Burlywood', color: const Color(0XFFdeb887)),
  ColorName(name: 'Burnt orange', color: const Color(0XFFcc5500)),
  ColorName(name: 'Burnt sienna', color: const Color(0XFFe97451)),
  ColorName(name: 'Burnt umber', color: const Color(0XFF8a3324)),
  ColorName(name: 'Byzantine', color: const Color(0XFFbd33a4)),
  ColorName(name: 'Byzantium', color: const Color(0XFF702963)),
  ColorName(name: 'CG Blue', color: const Color(0XFF007aa5)),
  ColorName(name: 'CG Red', color: const Color(0XFFe03c31)),
  ColorName(name: 'Cadet', color: const Color(0XFF536872)),
  ColorName(name: 'Cadet blue', color: const Color(0XFF5f9ea0)),
  ColorName(name: 'Cadet grey', color: const Color(0XFF91a3b0)),
  ColorName(name: 'Cadmium green', color: const Color(0XFF006b3c)),
  ColorName(name: 'Cadmium orange', color: const Color(0XFFed872d)),
  ColorName(name: 'Cadmium red', color: const Color(0XFFe30022)),
  ColorName(name: 'Cadmium yellow', color: const Color(0XFFfff600)),
  ColorName(name: 'Café au lait', color: const Color(0XFFa67b5b)),
  ColorName(name: 'Café noir', color: const Color(0XFF4b3621)),
  ColorName(name: 'Cal Poly Pomona green', color: const Color(0XFF1e4d2b)),
  ColorName(name: 'Cambridge Blue', color: const Color(0XFFa3c1ad)),
  ColorName(name: 'Camel', color: const Color(0XFFc19a6b)),
  ColorName(name: 'Camouflage green', color: const Color(0XFF78866b)),
  ColorName(name: 'Canary', color: const Color(0XFFffff99)),
  ColorName(name: 'Canary yellow', color: const Color(0XFFffef00)),
  ColorName(name: 'Candy apple red', color: const Color(0XFFff0800)),
  ColorName(name: 'Candy pink', color: const Color(0XFFe4717a)),
  ColorName(name: 'Capri', color: const Color(0XFF00bfff)),
  ColorName(name: 'Caput mortuum', color: const Color(0XFF592720)),
  ColorName(name: 'Cardinal', color: const Color(0XFFc41e3a)),
  ColorName(name: 'Caribbean green', color: const Color(0XFF00cc99)),
  ColorName(name: 'Carmine', color: const Color(0XFFff0040)),
  ColorName(name: 'Carmine pink', color: const Color(0XFFeb4c42)),
  ColorName(name: 'Carmine red', color: const Color(0XFFff0038)),
  ColorName(name: 'Carnation pink', color: const Color(0XFFffa6c9)),
  ColorName(name: 'Carnelian', color: const Color(0XFFb31b1b)),
  ColorName(name: 'Carolina blue', color: const Color(0XFF99badd)),
  ColorName(name: 'Carrot orange', color: const Color(0XFFed9121)),
  ColorName(name: 'Celadon', color: const Color(0XFFace1af)),
  ColorName(name: 'Celeste', color: const Color(0XFFb2ffff)),
  ColorName(name: 'Celestial blue', color: const Color(0XFF4997d0)),
  ColorName(name: 'Cerise', color: const Color(0XFFde3163)),
  ColorName(name: 'Cerise pink', color: const Color(0XFFec3b83)),
  ColorName(name: 'Cerulean', color: const Color(0XFF007ba7)),
  ColorName(name: 'Cerulean blue', color: const Color(0XFF2a52be)),
  ColorName(name: 'Chamoisee', color: const Color(0XFFa0785a)),
  ColorName(name: 'Champagne', color: const Color(0XFFfad6a5)),
  ColorName(name: 'Charcoal', color: const Color(0XFF36454f)),
  ColorName(name: 'Chartreuse', color: const Color(0XFF7fff00)),
  ColorName(name: 'Cherry', color: const Color(0XFFde3163)),
  ColorName(name: 'Cherry blossom pink', color: const Color(0XFFffb7c5)),
  ColorName(name: 'Chestnut', color: const Color(0XFFcd5c5c)),
  ColorName(name: 'Chocolate', color: const Color(0XFFd2691e)),
  ColorName(name: 'Chrome yellow', color: const Color(0XFFffa700)),
  ColorName(name: 'Cinereous', color: const Color(0XFF98817b)),
  ColorName(name: 'Cinnabar', color: const Color(0XFFe34234)),
  ColorName(name: 'Cinnamon', color: const Color(0XFFd2691e)),
  ColorName(name: 'Citrine', color: const Color(0XFFe4d00a)),
  ColorName(name: 'Classic rose', color: const Color(0XFFfbcce7)),
  ColorName(name: 'Cobalt', color: const Color(0XFF0047ab)),
  ColorName(name: 'Cocoa brown', color: const Color(0XFFd2691e)),
  ColorName(name: 'Coffee', color: const Color(0XFF6f4e37)),
  ColorName(name: 'Columbia blue', color: const Color(0XFF9bddff)),
  ColorName(name: 'Cool black', color: const Color(0XFF002e63)),
  ColorName(name: 'Cool grey', color: const Color(0XFF8c92ac)),
  ColorName(name: 'Copper', color: const Color(0XFFb87333)),
  ColorName(name: 'Copper rose', color: const Color(0XFF996666)),
  ColorName(name: 'Coquelicot', color: const Color(0XFFff3800)),
  ColorName(name: 'Coral', color: const Color(0XFFff7f50)),
  ColorName(name: 'Coral pink', color: const Color(0XFFf88379)),
  ColorName(name: 'Coral red', color: const Color(0XFFff4040)),
  ColorName(name: 'Cordovan', color: const Color(0XFF893f45)),
  ColorName(name: 'Corn', color: const Color(0XFFfbec5d)),
  ColorName(name: 'Cornell Red', color: const Color(0XFFb31b1b)),
  ColorName(name: 'Cornflower', color: const Color(0XFF9aceeb)),
  ColorName(name: 'Cornflower blue', color: const Color(0XFF6495ed)),
  ColorName(name: 'Cornsilk', color: const Color(0XFFfff8dc)),
  ColorName(name: 'Cosmic latte', color: const Color(0XFFfff8e7)),
  ColorName(name: 'Cotton candy', color: const Color(0XFFffbcd9)),
  ColorName(name: 'Cream', color: const Color(0XFFfffdd0)),
  ColorName(name: 'Crimson', color: const Color(0XFFdc143c)),
  ColorName(name: 'Crimson Red', color: const Color(0XFF990000)),
  ColorName(name: 'Crimson glory', color: const Color(0XFFbe0032)),
  ColorName(name: 'Cyan', color: const Color(0XFF00ffff)),
  ColorName(name: 'Daffodil', color: const Color(0XFFffff31)),
  ColorName(name: 'Dandelion', color: const Color(0XFFf0e130)),
  ColorName(name: 'Dark blue', color: const Color(0XFF00008b)),
  ColorName(name: 'Dark brown', color: const Color(0XFF654321)),
  ColorName(name: 'Dark byzantium', color: const Color(0XFF5d3954)),
  ColorName(name: 'Dark candy apple red', color: const Color(0XFFa40000)),
  ColorName(name: 'Dark cerulean', color: const Color(0XFF08457e)),
  ColorName(name: 'Dark chestnut', color: const Color(0XFF986960)),
  ColorName(name: 'Dark coral', color: const Color(0XFFcd5b45)),
  ColorName(name: 'Dark cyan', color: const Color(0XFF008b8b)),
  ColorName(name: 'Dark electric blue', color: const Color(0XFF536878)),
  ColorName(name: 'Dark goldenrod', color: const Color(0XFFb8860b)),
  ColorName(name: 'Dark gray', color: const Color(0XFFa9a9a9)),
  ColorName(name: 'Dark green', color: const Color(0XFF013220)),
  ColorName(name: 'Dark jungle green', color: const Color(0XFF1a2421)),
  ColorName(name: 'Dark khaki', color: const Color(0XFFbdb76b)),
  ColorName(name: 'Dark lava', color: const Color(0XFF483c32)),
  ColorName(name: 'Dark lavender', color: const Color(0XFF734f96)),
  ColorName(name: 'Dark magenta', color: const Color(0XFF8b008b)),
  ColorName(name: 'Dark midnight blue', color: const Color(0XFF003366)),
  ColorName(name: 'Dark olive green', color: const Color(0XFF556b2f)),
  ColorName(name: 'Dark orange', color: const Color(0XFFff8c00)),
  ColorName(name: 'Dark orchid', color: const Color(0XFF9932cc)),
  ColorName(name: 'Dark pastel blue', color: const Color(0XFF779ecb)),
  ColorName(name: 'Dark pastel green', color: const Color(0XFF03c03c)),
  ColorName(name: 'Dark pastel purple', color: const Color(0XFF966fd6)),
  ColorName(name: 'Dark pastel red', color: const Color(0XFFc23b22)),
  ColorName(name: 'Dark pink', color: const Color(0XFFe75480)),
  ColorName(name: 'Dark powder blue', color: const Color(0XFF003399)),
  ColorName(name: 'Dark raspberry', color: const Color(0XFF872657)),
  ColorName(name: 'Dark red', color: const Color(0XFF8b0000)),
  ColorName(name: 'Dark salmon', color: const Color(0XFFe9967a)),
  ColorName(name: 'Dark scarlet', color: const Color(0XFF560319)),
  ColorName(name: 'Dark sea green', color: const Color(0XFF8fbc8f)),
  ColorName(name: 'Dark sienna', color: const Color(0XFF3c1414)),
  ColorName(name: 'Dark slate blue', color: const Color(0XFF483d8b)),
  ColorName(name: 'Dark slate gray', color: const Color(0XFF2f4f4f)),
  ColorName(name: 'Dark spring green', color: const Color(0XFF177245)),
  ColorName(name: 'Dark tan', color: const Color(0XFF918151)),
  ColorName(name: 'Dark tangerine', color: const Color(0XFFffa812)),
  ColorName(name: 'Dark taupe', color: const Color(0XFF483c32)),
  ColorName(name: 'Dark terra cotta', color: const Color(0XFFcc4e5c)),
  ColorName(name: 'Dark turquoise', color: const Color(0XFF00ced1)),
  ColorName(name: 'Dark violet', color: const Color(0XFF9400d3)),
  ColorName(name: 'Dartmouth green', color: const Color(0XFF00693e)),
  ColorName(name: 'Davy grey', color: const Color(0XFF555555)),
  ColorName(name: 'Debian red', color: const Color(0XFFd70a53)),
  ColorName(name: 'Deep carmine', color: const Color(0XFFa9203e)),
  ColorName(name: 'Deep carmine pink', color: const Color(0XFFef3038)),
  ColorName(name: 'Deep carrot orange', color: const Color(0XFFe9692c)),
  ColorName(name: 'Deep cerise', color: const Color(0XFFda3287)),
  ColorName(name: 'Deep champagne', color: const Color(0XFFfad6a5)),
  ColorName(name: 'Deep chestnut', color: const Color(0XFFb94e48)),
  ColorName(name: 'Deep coffee', color: const Color(0XFF704241)),
  ColorName(name: 'Deep fuchsia', color: const Color(0XFFc154c1)),
  ColorName(name: 'Deep jungle green', color: const Color(0XFF004b49)),
  ColorName(name: 'Deep lilac', color: const Color(0XFF9955bb)),
  ColorName(name: 'Deep magenta', color: const Color(0XFFcc00cc)),
  ColorName(name: 'Deep peach', color: const Color(0XFFffcba4)),
  ColorName(name: 'Deep pink', color: const Color(0XFFff1493)),
  ColorName(name: 'Deep saffron', color: const Color(0XFFff9933)),
  ColorName(name: 'Deep sky blue', color: const Color(0XFF00bfff)),
  ColorName(name: 'Denim', color: const Color(0XFF1560bd)),
  ColorName(name: 'Desert', color: const Color(0XFFc19a6b)),
  ColorName(name: 'Desert sand', color: const Color(0XFFedc9af)),
  ColorName(name: 'Dim gray', color: const Color(0XFF696969)),
  ColorName(name: 'Dodger blue', color: const Color(0XFF1e90ff)),
  ColorName(name: 'Dogwood rose', color: const Color(0XFFd71868)),
  ColorName(name: 'Dollar bill', color: const Color(0XFF85bb65)),
  ColorName(name: 'Drab', color: const Color(0XFF967117)),
  ColorName(name: 'Duke blue', color: const Color(0XFF00009c)),
  ColorName(name: 'Earth yellow', color: const Color(0XFFe1a95f)),
  ColorName(name: 'Ecru', color: const Color(0XFFc2b280)),
  ColorName(name: 'Eggplant', color: const Color(0XFF614051)),
  ColorName(name: 'Eggshell', color: const Color(0XFFf0ead6)),
  ColorName(name: 'Egyptian blue', color: const Color(0XFF1034a6)),
  ColorName(name: 'Electric blue', color: const Color(0XFF7df9ff)),
  ColorName(name: 'Electric crimson', color: const Color(0XFFff003f)),
  ColorName(name: 'Electric cyan', color: const Color(0XFF00ffff)),
  ColorName(name: 'Electric green', color: const Color(0XFF00ff00)),
  ColorName(name: 'Electric indigo', color: const Color(0XFF6f00ff)),
  ColorName(name: 'Electric lavender', color: const Color(0XFFf4bbff)),
  ColorName(name: 'Electric lime', color: const Color(0XFFccff00)),
  ColorName(name: 'Electric purple', color: const Color(0XFFbf00ff)),
  ColorName(name: 'Electric ultramarine', color: const Color(0XFF3f00ff)),
  ColorName(name: 'Electric violet', color: const Color(0XFF8f00ff)),
  ColorName(name: 'Electric yellow', color: const Color(0XFFffff00)),
  ColorName(name: 'Emerald', color: const Color(0XFF50c878)),
  ColorName(name: 'Eton blue', color: const Color(0XFF96c8a2)),
  ColorName(name: 'Fallow', color: const Color(0XFFc19a6b)),
  ColorName(name: 'Falu red', color: const Color(0XFF801818)),
  ColorName(name: 'Famous', color: const Color(0XFFff00ff)),
  ColorName(name: 'Fandango', color: const Color(0XFFb53389)),
  ColorName(name: 'Fashion fuchsia', color: const Color(0XFFf400a1)),
  ColorName(name: 'Fawn', color: const Color(0XFFe5aa70)),
  ColorName(name: 'Feldgrau', color: const Color(0XFF4d5d53)),
  ColorName(name: 'Fern', color: const Color(0XFF71bc78)),
  ColorName(name: 'Fern green', color: const Color(0XFF4f7942)),
  ColorName(name: 'Ferrari Red', color: const Color(0XFFff2800)),
  ColorName(name: 'Field drab', color: const Color(0XFF6c541e)),
  ColorName(name: 'Fire engine red', color: const Color(0XFFce2029)),
  ColorName(name: 'Firebrick', color: const Color(0XFFb22222)),
  ColorName(name: 'Flame', color: const Color(0XFFe25822)),
  ColorName(name: 'Flamingo pink', color: const Color(0XFFfc8eac)),
  ColorName(name: 'Flavescent', color: const Color(0XFFf7e98e)),
  ColorName(name: 'Flax', color: const Color(0XFFeedc82)),
  ColorName(name: 'Floral white', color: const Color(0XFFfffaf0)),
  ColorName(name: 'Fluorescent orange', color: const Color(0XFFffbf00)),
  ColorName(name: 'Fluorescent pink', color: const Color(0XFFff1493)),
  ColorName(name: 'Fluorescent yellow', color: const Color(0XFFccff00)),
  ColorName(name: 'Folly', color: const Color(0XFFff004f)),
  ColorName(name: 'Forest green', color: const Color(0XFF228b22)),
  ColorName(name: 'French beige', color: const Color(0XFFa67b5b)),
  ColorName(name: 'French blue', color: const Color(0XFF0072bb)),
  ColorName(name: 'French lilac', color: const Color(0XFF86608e)),
  ColorName(name: 'French rose', color: const Color(0XFFf64a8a)),
  ColorName(name: 'Fuchsia', color: const Color(0XFFff00ff)),
  ColorName(name: 'Fuchsia pink', color: const Color(0XFFff77ff)),
  ColorName(name: 'Fulvous', color: const Color(0XFFe48400)),
  ColorName(name: 'Fuzzy Wuzzy', color: const Color(0XFFcc6666)),
  ColorName(name: 'Gainsboro', color: const Color(0XFFdcdcdc)),
  ColorName(name: 'Gamboge', color: const Color(0XFFe49b0f)),
  ColorName(name: 'Ghost white', color: const Color(0XFFf8f8ff)),
  ColorName(name: 'Ginger', color: const Color(0XFFb06500)),
  ColorName(name: 'Glaucous', color: const Color(0XFF6082b6)),
  ColorName(name: 'Glitter', color: const Color(0XFFe6e8fa)),
  ColorName(name: 'Gold', color: const Color(0XFFffd700)),
  ColorName(name: 'Golden brown', color: const Color(0XFF996515)),
  ColorName(name: 'Golden poppy', color: const Color(0XFFfcc200)),
  ColorName(name: 'Golden yellow', color: const Color(0XFFffdf00)),
  ColorName(name: 'Goldenrod', color: const Color(0XFFdaa520)),
  ColorName(name: 'Granny Smith Apple', color: const Color(0XFFa8e4a0)),
  ColorName(name: 'Gray', color: const Color(0XFF808080)),
  ColorName(name: 'Gray asparagus', color: const Color(0XFF465945)),
  ColorName(name: 'Green', color: const Color(0XFF00ff00)),
  ColorName(name: 'Green Blue', color: const Color(0XFF1164b4)),
  ColorName(name: 'Green yellow', color: const Color(0XFFadff2f)),
  ColorName(name: 'Grullo', color: const Color(0XFFa99a86)),
  ColorName(name: 'Guppie green', color: const Color(0XFF00ff7f)),
  ColorName(name: 'Halayà úbe', color: const Color(0XFF663854)),
  ColorName(name: 'Han blue', color: const Color(0XFF446ccf)),
  ColorName(name: 'Han purple', color: const Color(0XFF5218fa)),
  ColorName(name: 'Hansa yellow', color: const Color(0XFFe9d66b)),
  ColorName(name: 'Harlequin', color: const Color(0XFF3fff00)),
  ColorName(name: 'Harvard crimson', color: const Color(0XFFc90016)),
  ColorName(name: 'Harvest Gold', color: const Color(0XFFda9100)),
  ColorName(name: 'Heart Gold', color: const Color(0XFF808000)),
  ColorName(name: 'Heliotrope', color: const Color(0XFFdf73ff)),
  ColorName(name: 'Hollywood cerise', color: const Color(0XFFf400a1)),
  ColorName(name: 'Honeydew', color: const Color(0XFFf0fff0)),
  ColorName(name: 'Hooker green', color: const Color(0XFF49796b)),
  ColorName(name: 'Hot magenta', color: const Color(0XFFff1dce)),
  ColorName(name: 'Hot pink', color: const Color(0XFFff69b4)),
  ColorName(name: 'Hunter green', color: const Color(0XFF355e3b)),
  ColorName(name: 'Icterine', color: const Color(0XFFfcf75e)),
  ColorName(name: 'Inchworm', color: const Color(0XFFb2ec5d)),
  ColorName(name: 'India green', color: const Color(0XFF138808)),
  ColorName(name: 'Indian red', color: const Color(0XFFcd5c5c)),
  ColorName(name: 'Indian yellow', color: const Color(0XFFe3a857)),
  ColorName(name: 'Indigo', color: const Color(0XFF4b0082)),
  ColorName(name: 'International Klein Blue', color: const Color(0XFF002fa7)),
  ColorName(name: 'International orange', color: const Color(0XFFff4f00)),
  ColorName(name: 'Iris', color: const Color(0XFF5a4fcf)),
  ColorName(name: 'Isabelline', color: const Color(0XFFf4f0ec)),
  ColorName(name: 'Islamic green', color: const Color(0XFF009000)),
  ColorName(name: 'Ivory', color: const Color(0XFFfffff0)),
  ColorName(name: 'Jade', color: const Color(0XFF00a86b)),
  ColorName(name: 'Jasmine', color: const Color(0XFFf8de7e)),
  ColorName(name: 'Jasper', color: const Color(0XFFd73b3e)),
  ColorName(name: 'Jazzberry jam', color: const Color(0XFFa50b5e)),
  ColorName(name: 'Jonquil', color: const Color(0XFFfada5e)),
  ColorName(name: 'June bud', color: const Color(0XFFbdda57)),
  ColorName(name: 'Jungle green', color: const Color(0XFF29ab87)),
  ColorName(name: 'KU Crimson', color: const Color(0XFFe8000d)),
  ColorName(name: 'Kelly green', color: const Color(0XFF4cbb17)),
  ColorName(name: 'Khaki', color: const Color(0XFFc3b091)),
  ColorName(name: 'La Salle Green', color: const Color(0XFF087830)),
  ColorName(name: 'Languid lavender', color: const Color(0XFFd6cadd)),
  ColorName(name: 'Lapis lazuli', color: const Color(0XFF26619c)),
  ColorName(name: 'Laser Lemon', color: const Color(0XFFfefe22)),
  ColorName(name: 'Laurel green', color: const Color(0XFFa9ba9d)),
  ColorName(name: 'Lava', color: const Color(0XFFcf1020)),
  ColorName(name: 'Lavender', color: const Color(0XFFe6e6fa)),
  ColorName(name: 'Lavender blue', color: const Color(0XFFccccff)),
  ColorName(name: 'Lavender blush', color: const Color(0XFFfff0f5)),
  ColorName(name: 'Lavender gray', color: const Color(0XFFc4c3d0)),
  ColorName(name: 'Lavender indigo', color: const Color(0XFF9457eb)),
  ColorName(name: 'Lavender magenta', color: const Color(0XFFee82ee)),
  ColorName(name: 'Lavender mist', color: const Color(0XFFe6e6fa)),
  ColorName(name: 'Lavender pink', color: const Color(0XFFfbaed2)),
  ColorName(name: 'Lavender purple', color: const Color(0XFF967bb6)),
  ColorName(name: 'Lavender rose', color: const Color(0XFFfba0e3)),
  ColorName(name: 'Lawn green', color: const Color(0XFF7cfc00)),
  ColorName(name: 'Lemon', color: const Color(0XFFfff700)),
  ColorName(name: 'Lemon Yellow', color: const Color(0XFFfff44f)),
  ColorName(name: 'Lemon chiffon', color: const Color(0XFFfffacd)),
  ColorName(name: 'Lemon lime', color: const Color(0XFFbfff00)),
  ColorName(name: 'Light Crimson', color: const Color(0XFFf56991)),
  ColorName(name: 'Light Thulian pink', color: const Color(0XFFe68fac)),
  ColorName(name: 'Light apricot', color: const Color(0XFFfdd5b1)),
  ColorName(name: 'Light blue', color: const Color(0XFFadd8e6)),
  ColorName(name: 'Light brown', color: const Color(0XFFb5651d)),
  ColorName(name: 'Light carmine pink', color: const Color(0XFFe66771)),
  ColorName(name: 'Light coral', color: const Color(0XFFf08080)),
  ColorName(name: 'Light cornflower blue', color: const Color(0XFF93ccea)),
  ColorName(name: 'Light cyan', color: const Color(0XFFe0ffff)),
  ColorName(name: 'Light fuchsia pink', color: const Color(0XFFf984ef)),
  ColorName(name: 'Light goldenrod yellow', color: const Color(0XFFfafad2)),
  ColorName(name: 'Light gray', color: const Color(0XFFd3d3d3)),
  ColorName(name: 'Light green', color: const Color(0XFF90ee90)),
  ColorName(name: 'Light khaki', color: const Color(0XFFf0e68c)),
  ColorName(name: 'Light pastel purple', color: const Color(0XFFb19cd9)),
  ColorName(name: 'Light pink', color: const Color(0XFFffb6c1)),
  ColorName(name: 'Light salmon', color: const Color(0XFFffa07a)),
  ColorName(name: 'Light salmon pink', color: const Color(0XFFff9999)),
  ColorName(name: 'Light sea green', color: const Color(0XFF20b2aa)),
  ColorName(name: 'Light sky blue', color: const Color(0XFF87cefa)),
  ColorName(name: 'Light slate gray', color: const Color(0XFF778899)),
  ColorName(name: 'Light taupe', color: const Color(0XFFb38b6d)),
  ColorName(name: 'Light yellow', color: const Color(0XFFffffed)),
  ColorName(name: 'Lilac', color: const Color(0XFFc8a2c8)),
  ColorName(name: 'Lime', color: const Color(0XFFbfff00)),
  ColorName(name: 'Lime green', color: const Color(0XFF32cd32)),
  ColorName(name: 'Lincoln green', color: const Color(0XFF195905)),
  ColorName(name: 'Linen', color: const Color(0XFFfaf0e6)),
  ColorName(name: 'Lion', color: const Color(0XFFc19a6b)),
  ColorName(name: 'Liver', color: const Color(0XFF534b4f)),
  ColorName(name: 'Lust', color: const Color(0XFFe62020)),
  ColorName(name: 'MSU Green', color: const Color(0XFF18453b)),
  ColorName(name: 'Macaroni and Cheese', color: const Color(0XFFffbd88)),
  ColorName(name: 'Magenta', color: const Color(0XFFff00ff)),
  ColorName(name: 'Magic mint', color: const Color(0XFFaaf0d1)),
  ColorName(name: 'Magnolia', color: const Color(0XFFf8f4ff)),
  ColorName(name: 'Mahogany', color: const Color(0XFFc04000)),
  ColorName(name: 'Maize', color: const Color(0XFFfbec5d)),
  ColorName(name: 'Majorelle Blue', color: const Color(0XFF6050dc)),
  ColorName(name: 'Malachite', color: const Color(0XFF0bda51)),
  ColorName(name: 'Manatee', color: const Color(0XFF979aaa)),
  ColorName(name: 'Mango Tango', color: const Color(0XFFff8243)),
  ColorName(name: 'Mantis', color: const Color(0XFF74c365)),
  ColorName(name: 'Maroon', color: const Color(0XFF800000)),
  ColorName(name: 'Mauve', color: const Color(0XFFe0b0ff)),
  ColorName(name: 'Mauve taupe', color: const Color(0XFF915f6d)),
  ColorName(name: 'Mauvelous', color: const Color(0XFFef98aa)),
  ColorName(name: 'Maya blue', color: const Color(0XFF73c2fb)),
  ColorName(name: 'Meat brown', color: const Color(0XFFe5b73b)),
  ColorName(name: 'Medium Persian blue', color: const Color(0XFF0067a5)),
  ColorName(name: 'Medium aquamarine', color: const Color(0XFF66ddaa)),
  ColorName(name: 'Medium blue', color: const Color(0XFF0000cd)),
  ColorName(name: 'Medium candy apple red', color: const Color(0XFFe2062c)),
  ColorName(name: 'Medium carmine', color: const Color(0XFFaf4035)),
  ColorName(name: 'Medium champagne', color: const Color(0XFFf3e5ab)),
  ColorName(name: 'Medium electric blue', color: const Color(0XFF035096)),
  ColorName(name: 'Medium jungle green', color: const Color(0XFF1c352d)),
  ColorName(name: 'Medium lavender magenta', color: const Color(0XFFdda0dd)),
  ColorName(name: 'Medium orchid', color: const Color(0XFFba55d3)),
  ColorName(name: 'Medium purple', color: const Color(0XFF9370db)),
  ColorName(name: 'Medium red violet', color: const Color(0XFFbb3385)),
  ColorName(name: 'Medium sea green', color: const Color(0XFF3cb371)),
  ColorName(name: 'Medium slate blue', color: const Color(0XFF7b68ee)),
  ColorName(name: 'Medium spring bud', color: const Color(0XFFc9dc87)),
  ColorName(name: 'Medium spring green', color: const Color(0XFF00fa9a)),
  ColorName(name: 'Medium taupe', color: const Color(0XFF674c47)),
  ColorName(name: 'Medium teal blue', color: const Color(0XFF0054b4)),
  ColorName(name: 'Medium turquoise', color: const Color(0XFF48d1cc)),
  ColorName(name: 'Medium violet red', color: const Color(0XFFc71585)),
  ColorName(name: 'Melon', color: const Color(0XFFfdbcb4)),
  ColorName(name: 'Midnight blue', color: const Color(0XFF191970)),
  ColorName(name: 'Midnight green', color: const Color(0XFF004953)),
  ColorName(name: 'Mikado yellow', color: const Color(0XFFffc40c)),
  ColorName(name: 'Mint', color: const Color(0XFF3eb489)),
  ColorName(name: 'Mint cream', color: const Color(0XFFf5fffa)),
  ColorName(name: 'Mint green', color: const Color(0XFF98ff98)),
  ColorName(name: 'Misty rose', color: const Color(0XFFffe4e1)),
  ColorName(name: 'Moccasin', color: const Color(0XFFfaebd7)),
  ColorName(name: 'Mode beige', color: const Color(0XFF967117)),
  ColorName(name: 'Moonstone blue', color: const Color(0XFF73a9c2)),
  ColorName(name: 'Mordant red 19', color: const Color(0XFFae0c00)),
  ColorName(name: 'Moss green', color: const Color(0XFFaddfad)),
  ColorName(name: 'Mountain Meadow', color: const Color(0XFF30ba8f)),
  ColorName(name: 'Mountbatten pink', color: const Color(0XFF997a8d)),
  ColorName(name: 'Mulberry', color: const Color(0XFFc54b8c)),
  ColorName(name: 'Munsell', color: const Color(0XFFf2f3f4)),
  ColorName(name: 'Mustard', color: const Color(0XFFffdb58)),
  ColorName(name: 'Myrtle', color: const Color(0XFF21421e)),
  ColorName(name: 'Nadeshiko pink', color: const Color(0XFFf6adc6)),
  ColorName(name: 'Napier green', color: const Color(0XFF2a8000)),
  ColorName(name: 'Naples yellow', color: const Color(0XFFfada5e)),
  ColorName(name: 'Navajo white', color: const Color(0XFFffdead)),
  ColorName(name: 'Navy blue', color: const Color(0XFF000080)),
  ColorName(name: 'Neon Carrot', color: const Color(0XFFffa343)),
  ColorName(name: 'Neon fuchsia', color: const Color(0XFFfe59c2)),
  ColorName(name: 'Neon green', color: const Color(0XFF39ff14)),
  ColorName(name: 'Non-photo blue', color: const Color(0XFFa4dded)),
  ColorName(name: 'North Texas Green', color: const Color(0XFF059033)),
  ColorName(name: 'Ocean Boat Blue', color: const Color(0XFF0077be)),
  ColorName(name: 'Ochre', color: const Color(0XFFcc7722)),
  ColorName(name: 'Office green', color: const Color(0XFF008000)),
  ColorName(name: 'Old gold', color: const Color(0XFFcfb53b)),
  ColorName(name: 'Old lace', color: const Color(0XFFfdf5e6)),
  ColorName(name: 'Old lavender', color: const Color(0XFF796878)),
  ColorName(name: 'Old mauve', color: const Color(0XFF673147)),
  ColorName(name: 'Old rose', color: const Color(0XFFc08081)),
  ColorName(name: 'Olive', color: const Color(0XFF808000)),
  ColorName(name: 'Olive Drab', color: const Color(0XFF6b8e23)),
  ColorName(name: 'Olive Green', color: const Color(0XFFbab86c)),
  ColorName(name: 'Olivine', color: const Color(0XFF9ab973)),
  ColorName(name: 'Onyx', color: const Color(0XFF0f0f0f)),
  ColorName(name: 'Opera mauve', color: const Color(0XFFb784a7)),
  ColorName(name: 'Orange', color: const Color(0XFFffa500)),
  ColorName(name: 'Orange Yellow', color: const Color(0XFFf8d568)),
  ColorName(name: 'Orange peel', color: const Color(0XFFff9f00)),
  ColorName(name: 'Orange red', color: const Color(0XFFff4500)),
  ColorName(name: 'Orchid', color: const Color(0XFFda70d6)),
  ColorName(name: 'Otter brown', color: const Color(0XFF654321)),
  ColorName(name: 'Outer Space', color: const Color(0XFF414a4c)),
  ColorName(name: 'Outrageous Orange', color: const Color(0XFFff6e4a)),
  ColorName(name: 'Oxford Blue', color: const Color(0XFF002147)),
  ColorName(name: 'Pacific Blue', color: const Color(0XFF1ca9c9)),
  ColorName(name: 'Pakistan green', color: const Color(0XFF006600)),
  ColorName(name: 'Palatinate blue', color: const Color(0XFF273be2)),
  ColorName(name: 'Palatinate purple', color: const Color(0XFF682860)),
  ColorName(name: 'Pale aqua', color: const Color(0XFFbcd4e6)),
  ColorName(name: 'Pale blue', color: const Color(0XFFafeeee)),
  ColorName(name: 'Pale brown', color: const Color(0XFF987654)),
  ColorName(name: 'Pale carmine', color: const Color(0XFFaf4035)),
  ColorName(name: 'Pale cerulean', color: const Color(0XFF9bc4e2)),
  ColorName(name: 'Pale chestnut', color: const Color(0XFFddadaf)),
  ColorName(name: 'Pale copper', color: const Color(0XFFda8a67)),
  ColorName(name: 'Pale cornflower blue', color: const Color(0XFFabcdef)),
  ColorName(name: 'Pale gold', color: const Color(0XFFe6be8a)),
  ColorName(name: 'Pale goldenrod', color: const Color(0XFFeee8aa)),
  ColorName(name: 'Pale green', color: const Color(0XFF98fb98)),
  ColorName(name: 'Pale lavender', color: const Color(0XFFdcd0ff)),
  ColorName(name: 'Pale magenta', color: const Color(0XFFf984e5)),
  ColorName(name: 'Pale pink', color: const Color(0XFFfadadd)),
  ColorName(name: 'Pale plum', color: const Color(0XFFdda0dd)),
  ColorName(name: 'Pale red violet', color: const Color(0XFFdb7093)),
  ColorName(name: 'Pale robin egg blue', color: const Color(0XFF96ded1)),
  ColorName(name: 'Pale silver', color: const Color(0XFFc9c0bb)),
  ColorName(name: 'Pale spring bud', color: const Color(0XFFecebbd)),
  ColorName(name: 'Pale taupe', color: const Color(0XFFbc987e)),
  ColorName(name: 'Pale violet red', color: const Color(0XFFdb7093)),
  ColorName(name: 'Pansy purple', color: const Color(0XFF78184a)),
  ColorName(name: 'Papaya whip', color: const Color(0XFFffefd5)),
  ColorName(name: 'Paris Green', color: const Color(0XFF50c878)),
  ColorName(name: 'Pastel blue', color: const Color(0XFFaec6cf)),
  ColorName(name: 'Pastel brown', color: const Color(0XFF836953)),
  ColorName(name: 'Pastel gray', color: const Color(0XFFcfcfc4)),
  ColorName(name: 'Pastel green', color: const Color(0XFF77dd77)),
  ColorName(name: 'Pastel magenta', color: const Color(0XFFf49ac2)),
  ColorName(name: 'Pastel orange', color: const Color(0XFFffb347)),
  ColorName(name: 'Pastel pink', color: const Color(0XFFffd1dc)),
  ColorName(name: 'Pastel purple', color: const Color(0XFFb39eb5)),
  ColorName(name: 'Pastel red', color: const Color(0XFFff6961)),
  ColorName(name: 'Pastel violet', color: const Color(0XFFcb99c9)),
  ColorName(name: 'Pastel yellow', color: const Color(0XFFfdfd96)),
  ColorName(name: 'Patriarch', color: const Color(0XFF800080)),
  ColorName(name: 'Payne grey', color: const Color(0XFF536878)),
  ColorName(name: 'Peach', color: const Color(0XFFffe5b4)),
  ColorName(name: 'Peach puff', color: const Color(0XFFffdab9)),
  ColorName(name: 'Peach yellow', color: const Color(0XFFfadfad)),
  ColorName(name: 'Pear', color: const Color(0XFFd1e231)),
  ColorName(name: 'Pearl', color: const Color(0XFFeae0c8)),
  ColorName(name: 'Pearl Aqua', color: const Color(0XFF88d8c0)),
  ColorName(name: 'Peridot', color: const Color(0XFFe6e200)),
  ColorName(name: 'Periwinkle', color: const Color(0XFFccccff)),
  ColorName(name: 'Persian blue', color: const Color(0XFF1c39bb)),
  ColorName(name: 'Persian indigo', color: const Color(0XFF32127a)),
  ColorName(name: 'Persian orange', color: const Color(0XFFd99058)),
  ColorName(name: 'Persian pink', color: const Color(0XFFf77fbe)),
  ColorName(name: 'Persian plum', color: const Color(0XFF701c1c)),
  ColorName(name: 'Persian red', color: const Color(0XFFcc3333)),
  ColorName(name: 'Persian rose', color: const Color(0XFFfe28a2)),
  ColorName(name: 'Phlox', color: const Color(0XFFdf00ff)),
  ColorName(name: 'Phthalo blue', color: const Color(0XFF000f89)),
  ColorName(name: 'Phthalo green', color: const Color(0XFF123524)),
  ColorName(name: 'Piggy pink', color: const Color(0XFFfddde6)),
  ColorName(name: 'Pine green', color: const Color(0XFF01796f)),
  ColorName(name: 'Pink', color: const Color(0XFFffc0cb)),
  ColorName(name: 'Pink Flamingo', color: const Color(0XFFfc74fd)),
  ColorName(name: 'Pink Sherbet', color: const Color(0XFFf78fa7)),
  ColorName(name: 'Pink pearl', color: const Color(0XFFe7accf)),
  ColorName(name: 'Pistachio', color: const Color(0XFF93c572)),
  ColorName(name: 'Platinum', color: const Color(0XFFe5e4e2)),
  ColorName(name: 'Plum', color: const Color(0XFFdda0dd)),
  ColorName(name: 'Portland Orange', color: const Color(0XFFff5a36)),
  ColorName(name: 'Powder blue', color: const Color(0XFFb0e0e6)),
  ColorName(name: 'Princeton orange', color: const Color(0XFFff8f00)),
  ColorName(name: 'Prussian blue', color: const Color(0XFF003153)),
  ColorName(name: 'Psychedelic purple', color: const Color(0XFFdf00ff)),
  ColorName(name: 'Puce', color: const Color(0XFFcc8899)),
  ColorName(name: 'Pumpkin', color: const Color(0XFFff7518)),
  ColorName(name: 'Purple', color: const Color(0XFF800080)),
  ColorName(name: 'Purple Heart', color: const Color(0XFF69359c)),
  ColorName(name: "Purple Mountain's Majesty", color: const Color(0XFF9d81ba)),
  ColorName(name: 'Purple mountain majesty', color: const Color(0XFF9678b6)),
  ColorName(name: 'Purple pizzazz', color: const Color(0XFFfe4eda)),
  ColorName(name: 'Purple taupe', color: const Color(0XFF50404d)),
  ColorName(name: 'Rackley', color: const Color(0XFF5d8aa8)),
  ColorName(name: 'Radical Red', color: const Color(0XFFff355e)),
  ColorName(name: 'Raspberry', color: const Color(0XFFe30b5d)),
  ColorName(name: 'Raspberry glace', color: const Color(0XFF915f6d)),
  ColorName(name: 'Raspberry pink', color: const Color(0XFFe25098)),
  ColorName(name: 'Raspberry rose', color: const Color(0XFFb3446c)),
  ColorName(name: 'Raw Sienna', color: const Color(0XFFd68a59)),
  ColorName(name: 'Razzle dazzle rose', color: const Color(0XFFff33cc)),
  ColorName(name: 'Razzmatazz', color: const Color(0XFFe3256b)),
  ColorName(name: 'Red', color: const Color(0XFFff0000)),
  ColorName(name: 'Red Orange', color: const Color(0XFFff5349)),
  ColorName(name: 'Red brown', color: const Color(0XFFa52a2a)),
  ColorName(name: 'Red violet', color: const Color(0XFFc71585)),
  ColorName(name: 'Rich black', color: const Color(0XFF004040)),
  ColorName(name: 'Rich carmine', color: const Color(0XFFd70040)),
  ColorName(name: 'Rich electric blue', color: const Color(0XFF0892d0)),
  ColorName(name: 'Rich lilac', color: const Color(0XFFb666d2)),
  ColorName(name: 'Rich maroon', color: const Color(0XFFb03060)),
  ColorName(name: 'Rifle green', color: const Color(0XFF414833)),
  ColorName(name: "Robin's Egg Blue", color: const Color(0XFF1fcecb)),
  ColorName(name: 'Rose', color: const Color(0XFFff007f)),
  ColorName(name: 'Rose bonbon', color: const Color(0XFFf9429e)),
  ColorName(name: 'Rose ebony', color: const Color(0XFF674846)),
  ColorName(name: 'Rose gold', color: const Color(0XFFb76e79)),
  ColorName(name: 'Rose madder', color: const Color(0XFFe32636)),
  ColorName(name: 'Rose pink', color: const Color(0XFFff66cc)),
  ColorName(name: 'Rose quartz', color: const Color(0XFFaa98a9)),
  ColorName(name: 'Rose taupe', color: const Color(0XFF905d5d)),
  ColorName(name: 'Rose vale', color: const Color(0XFFab4e52)),
  ColorName(name: 'Rosewood', color: const Color(0XFF65000b)),
  ColorName(name: 'Rosso corsa', color: const Color(0XFFd40000)),
  ColorName(name: 'Rosy brown', color: const Color(0XFFbc8f8f)),
  ColorName(name: 'Royal azure', color: const Color(0XFF0038a8)),
  ColorName(name: 'Royal blue', color: const Color(0XFF4169e1)),
  ColorName(name: 'Royal fuchsia', color: const Color(0XFFca2c92)),
  ColorName(name: 'Royal purple', color: const Color(0XFF7851a9)),
  ColorName(name: 'Ruby', color: const Color(0XFFe0115f)),
  ColorName(name: 'Ruddy', color: const Color(0XFFff0028)),
  ColorName(name: 'Ruddy brown', color: const Color(0XFFbb6528)),
  ColorName(name: 'Ruddy pink', color: const Color(0XFFe18e96)),
  ColorName(name: 'Rufous', color: const Color(0XFFa81c07)),
  ColorName(name: 'Russet', color: const Color(0XFF80461b)),
  ColorName(name: 'Rust', color: const Color(0XFFb7410e)),
  ColorName(name: 'Sacramento State green', color: const Color(0XFF00563f)),
  ColorName(name: 'Saddle brown', color: const Color(0XFF8b4513)),
  ColorName(name: 'Safety orange', color: const Color(0XFFff6700)),
  ColorName(name: 'Saffron', color: const Color(0XFFf4c430)),
  ColorName(name: 'Saint Patrick Blue', color: const Color(0XFF23297a)),
  ColorName(name: 'Salmon', color: const Color(0XFFff8c69)),
  ColorName(name: 'Salmon pink', color: const Color(0XFFff91a4)),
  ColorName(name: 'Sand', color: const Color(0XFFc2b280)),
  ColorName(name: 'Sand dune', color: const Color(0XFF967117)),
  ColorName(name: 'Sandstorm', color: const Color(0XFFecd540)),
  ColorName(name: 'Sandy brown', color: const Color(0XFFf4a460)),
  ColorName(name: 'Sandy taupe', color: const Color(0XFF967117)),
  ColorName(name: 'Sap green', color: const Color(0XFF507d2a)),
  ColorName(name: 'Sapphire', color: const Color(0XFF0f52ba)),
  ColorName(name: 'Satin sheen gold', color: const Color(0XFFcba135)),
  ColorName(name: 'Scarlet', color: const Color(0XFFff2400)),
  ColorName(name: 'School bus yellow', color: const Color(0XFFffd800)),
  ColorName(name: 'Screamin Green', color: const Color(0XFF76ff7a)),
  ColorName(name: 'Sea blue', color: const Color(0XFF006994)),
  ColorName(name: 'Sea green', color: const Color(0XFF2e8b57)),
  ColorName(name: 'Seal brown', color: const Color(0XFF321414)),
  ColorName(name: 'Seashell', color: const Color(0XFFfff5ee)),
  ColorName(name: 'Selective yellow', color: const Color(0XFFffba00)),
  ColorName(name: 'Sepia', color: const Color(0XFF704214)),
  ColorName(name: 'Shadow', color: const Color(0XFF8a795d)),
  ColorName(name: 'Shamrock', color: const Color(0XFF45cea2)),
  ColorName(name: 'Shamrock green', color: const Color(0XFF009e60)),
  ColorName(name: 'Shocking pink', color: const Color(0XFFfc0fc0)),
  ColorName(name: 'Sienna', color: const Color(0XFF882d17)),
  ColorName(name: 'Silver', color: const Color(0XFFc0c0c0)),
  ColorName(name: 'Sinopia', color: const Color(0XFFcb410b)),
  ColorName(name: 'Skobeloff', color: const Color(0XFF007474)),
  ColorName(name: 'Sky blue', color: const Color(0XFF87ceeb)),
  ColorName(name: 'Sky magenta', color: const Color(0XFFcf71af)),
  ColorName(name: 'Slate blue', color: const Color(0XFF6a5acd)),
  ColorName(name: 'Slate gray', color: const Color(0XFF708090)),
  ColorName(name: 'Smalt', color: const Color(0XFF003399)),
  ColorName(name: 'Smokey topaz', color: const Color(0XFF933d41)),
  ColorName(name: 'Smoky black', color: const Color(0XFF100c08)),
  ColorName(name: 'Snow', color: const Color(0XFFfffafa)),
  ColorName(name: 'Spiro Disco Ball', color: const Color(0XFF0fc0fc)),
  ColorName(name: 'Spring bud', color: const Color(0XFFa7fc00)),
  ColorName(name: 'Spring green', color: const Color(0XFF00ff7f)),
  ColorName(name: 'Steel blue', color: const Color(0XFF4682b4)),
  ColorName(name: 'Stil de grain yellow', color: const Color(0XFFfada5e)),
  ColorName(name: 'Stizza', color: const Color(0XFF990000)),
  ColorName(name: 'Stormcloud', color: const Color(0XFF008080)),
  ColorName(name: 'Straw', color: const Color(0XFFe4d96f)),
  ColorName(name: 'Sunglow', color: const Color(0XFFffcc33)),
  ColorName(name: 'Sunset', color: const Color(0XFFfad6a5)),
  ColorName(name: 'Sunset Orange', color: const Color(0XFFfd5e53)),
  ColorName(name: 'Tan', color: const Color(0XFFd2b48c)),
  ColorName(name: 'Tangelo', color: const Color(0XFFf94d00)),
  ColorName(name: 'Tangerine', color: const Color(0XFFf28500)),
  ColorName(name: 'Tangerine yellow', color: const Color(0XFFffcc00)),
  ColorName(name: 'Taupe', color: const Color(0XFF483c32)),
  ColorName(name: 'Taupe gray', color: const Color(0XFF8b8589)),
  ColorName(name: 'Tawny', color: const Color(0XFFcd5700)),
  ColorName(name: 'Tea green', color: const Color(0XFFd0f0c0)),
  ColorName(name: 'Tea rose', color: const Color(0XFFf4c2c2)),
  ColorName(name: 'Teal', color: const Color(0XFF008080)),
  ColorName(name: 'Teal blue', color: const Color(0XFF367588)),
  ColorName(name: 'Teal green', color: const Color(0XFF006d5b)),
  ColorName(name: 'Terra cotta', color: const Color(0XFFe2725b)),
  ColorName(name: 'Thistle', color: const Color(0XFFd8bfd8)),
  ColorName(name: 'Thulian pink', color: const Color(0XFFde6fa1)),
  ColorName(name: 'Tickle Me Pink', color: const Color(0XFFfc89ac)),
  ColorName(name: 'Tiffany Blue', color: const Color(0XFF0abab5)),
  ColorName(name: 'Tiger eye', color: const Color(0XFFe08d3c)),
  ColorName(name: 'Timberwolf', color: const Color(0XFFdbd7d2)),
  ColorName(name: 'Titanium yellow', color: const Color(0XFFeee600)),
  ColorName(name: 'Tomato', color: const Color(0XFFff6347)),
  ColorName(name: 'Toolbox', color: const Color(0XFF746cc0)),
  ColorName(name: 'Topaz', color: const Color(0XFFffc87c)),
  ColorName(name: 'Tractor red', color: const Color(0XFFfd0e35)),
  ColorName(name: 'Trolley Grey', color: const Color(0XFF808080)),
  ColorName(name: 'Tropical rain forest', color: const Color(0XFF00755e)),
  ColorName(name: 'True Blue', color: const Color(0XFF0073cf)),
  ColorName(name: 'Tufts Blue', color: const Color(0XFF417dc1)),
  ColorName(name: 'Tumbleweed', color: const Color(0XFFdeaa88)),
  ColorName(name: 'Turkish rose', color: const Color(0XFFb57281)),
  ColorName(name: 'Turquoise', color: const Color(0XFF30d5c8)),
  ColorName(name: 'Turquoise blue', color: const Color(0XFF00ffef)),
  ColorName(name: 'Turquoise green', color: const Color(0XFFa0d6b4)),
  ColorName(name: 'Tuscan red', color: const Color(0XFF66424d)),
  ColorName(name: 'Twilight lavender', color: const Color(0XFF8a496b)),
  ColorName(name: 'Tyrian purple', color: const Color(0XFF66023c)),
  ColorName(name: 'UA blue', color: const Color(0XFF0033aa)),
  ColorName(name: 'UA red', color: const Color(0XFFd9004c)),
  ColorName(name: 'UCLA Blue', color: const Color(0XFF536895)),
  ColorName(name: 'UCLA Gold', color: const Color(0XFFffb300)),
  ColorName(name: 'UFO Green', color: const Color(0XFF3cd070)),
  ColorName(name: 'UP Forest green', color: const Color(0XFF014421)),
  ColorName(name: 'UP Maroon', color: const Color(0XFF7b1113)),
  ColorName(name: 'USC Cardinal', color: const Color(0XFF990000)),
  ColorName(name: 'USC Gold', color: const Color(0XFFffcc00)),
  ColorName(name: 'Ube', color: const Color(0XFF8878c3)),
  ColorName(name: 'Ultra pink', color: const Color(0XFFff6fff)),
  ColorName(name: 'Ultramarine', color: const Color(0XFF120a8f)),
  ColorName(name: 'Ultramarine blue', color: const Color(0XFF4166f5)),
  ColorName(name: 'Umber', color: const Color(0XFF635147)),
  ColorName(name: 'United Nations blue', color: const Color(0XFF5b92e5)),
  ColorName(
      name: 'University of California Gold', color: const Color(0XFFb78727)),
  ColorName(name: 'Unmellow Yellow', color: const Color(0XFFffff66)),
  ColorName(name: 'Upsdell red', color: const Color(0XFFae2029)),
  ColorName(name: 'Urobilin', color: const Color(0XFFe1ad21)),
  ColorName(name: 'Utah Crimson', color: const Color(0XFFd3003f)),
  ColorName(name: 'Vanilla', color: const Color(0XFFf3e5ab)),
  ColorName(name: 'Vegas gold', color: const Color(0XFFc5b358)),
  ColorName(name: 'Venetian red', color: const Color(0XFFc80815)),
  ColorName(name: 'Verdigris', color: const Color(0XFF43b3ae)),
  ColorName(name: 'Vermilion', color: const Color(0XFFe34234)),
  ColorName(name: 'Veronica', color: const Color(0XFFa020f0)),
  ColorName(name: 'Violet', color: const Color(0XFFee82ee)),
  ColorName(name: 'Violet Blue', color: const Color(0XFF324ab2)),
  ColorName(name: 'Violet Red', color: const Color(0XFFf75394)),
  ColorName(name: 'Viridian', color: const Color(0XFF40826d)),
  ColorName(name: 'Vivid auburn', color: const Color(0XFF922724)),
  ColorName(name: 'Vivid burgundy', color: const Color(0XFF9f1d35)),
  ColorName(name: 'Vivid cerise', color: const Color(0XFFda1d81)),
  ColorName(name: 'Vivid tangerine', color: const Color(0XFFffa089)),
  ColorName(name: 'Vivid violet', color: const Color(0XFF9f00ff)),
  ColorName(name: 'Warm black', color: const Color(0XFF004242)),
  ColorName(name: 'Waterspout', color: const Color(0XFF00ffff)),
  ColorName(name: 'Wenge', color: const Color(0XFF645452)),
  ColorName(name: 'Wheat', color: const Color(0XFFf5deb3)),
  ColorName(name: 'White', color: const Color(0XFFffffff)),
  ColorName(name: 'White smoke', color: const Color(0XFFf5f5f5)),
  ColorName(name: 'Wild Strawberry', color: const Color(0XFFff43a4)),
  ColorName(name: 'Wild Watermelon', color: const Color(0XFFfc6c85)),
  ColorName(name: 'Wild blue yonder', color: const Color(0XFFa2add0)),
  ColorName(name: 'Wine', color: const Color(0XFF722f37)),
  ColorName(name: 'Wisteria', color: const Color(0XFFc9a0dc)),
  ColorName(name: 'Xanadu', color: const Color(0XFF738678)),
  ColorName(name: 'Yale Blue', color: const Color(0XFF0f4d92)),
  ColorName(name: 'Yellow', color: const Color(0XFFffff00)),
  ColorName(name: 'Yellow Orange', color: const Color(0XFFffae42)),
  ColorName(name: 'Yellow green', color: const Color(0XFF9acd32)),
  ColorName(name: 'Zaffre', color: const Color(0XFF0014a8)),
  ColorName(name: 'Zinnwaldite brown', color: const Color(0XFF2c1608)),
];
